project:
  type: website
  output-dir: _site

website:
  title: "Nandani Arora"
  navbar:
    left:
      - text: About Me
        href: about.html
      - text: Education
        href: Education.html
      - text: Professional Experience
        href: Professional Experience.html
      - text: Skills & Certifications
        href: Skills & Certifications.html
      - text: Projects
        href: Projects.html
      - text: Contact
        href: Contact.html
      - text: Leadership & Community Service
        href: Leadership.html
  

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css

